- name: Neovim snaps
  community.general.snap:
    name:
      - nvim
    classic: true
  become: true
  when: ansible_distribution in ["Ubuntu", "Archlinux", "Fedora"]




####################
###   NVChad     ### 
####################

### Making Directories
- name: Creates directory (LINUX)
  file:
    path: "{{ item }}"
    state: directory
    owner: rocket
    group: rocket
    mode: 0775
    recurse: yes
  with_items:
  - /home/rocket/.config/nvim
  when: ansible_distribution in ["Debian", "Ubuntu", "Archlinux", "Fedora", "Pop!_OS"]


- name: clone NVChad
  git:
    repo: https://github.com/NvChad/NvChad
    dest: /home/rocket/.config/nvim
    clone: yes
    update: no
  become_user: rocket
  when: ansible_distribution in ["Ubuntu", "Archlinux", "Fedora"]