- name: system setup | tweaks | add flatpak support
  package:
    name: flatpak
    state: present
    
- name: add flathub remote repo
  become_user: rocket
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present

