#####################
# Dependencies      #
#####################
# FYI Dash to dock extension must be installed on Distro (build from source in bootstrap)
# might need these as dependencies   
#- dbus-tools 
#- dbus-daemon


- name: Installing Flatpaks
  become_user: rocket
  flatpak:
    name: 
      - com.mattjakeman.ExtensionManager
    method: user
    state: present
      


- name: Install Dconf
  package: 
    name:
      - dconf-editor
      - "{{ dconf_package }}" # Cli Version
    state: latest
    update_cache: yes
 
  

- name: Install Deconf Dependencies with python-pip
  ansible.builtin.pip:
    name: 
      - psutil
  


########################################
# Dash to Dock Position  and Behaviour    #
########################################

- name: move applauncher button to the top
  become_user: rocket
  dconf: 
    key: "/org/gnome/shell/extensions/dash-to-dock/show-apps-at-top"
    value: "true"

- name: Do not extend height
  become_user: rocket
  dconf: 
    key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
    value: "false"
      
- name: move Dash to the bottom
  become_user: rocket
  dconf: 
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'BOTTOM'"



- name: Enable minimise when clicking on app in dock
  become_user: rocket
  dconf: 
    key: "/org/gnome/shell/extensions/dash-to-dock/click-action"
    value: "'minimize'"



#####################
# terminal settings #
#####################


- name: terminal transparency
  become_user: rocket
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-transparent-background"
    value: "true"


- name: terminal transparency percentage
  become_user: rocket
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent"
    value: "5"

- name: terminal bright bold
  become_user: rocket
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/bold-is-bright"
    value: "true"

- name: terminal scrollback lines
  become_user: rocket
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollback-lines"
    value: "1000000"

- name: terminal find shortcut
  become_user: rocket
  dconf:
    key: "/org/gnome/terminal/legacy/keybindings/find"
    value: "'<Control>f'"




#####################
# peripherals      #
#####################

# Mouse Natural Scrolling
- name: disable natural scrolling (mouse)
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "false"



# Touchpad Laptop Natural Scrolling
- name: disable natural scrolling (touchpad)
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"
  when: ansible_local['custom']['device']['dev'] in ["rogstrix-lap"]


- name: gnome | peripherals | enable cursor acceleration (mouse)
  tags: gnome,mouse,peripherals
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "'adaptive'"

- name: gnome | peripherals | increase cursor speed (mouse)
  tags: gnome,mouse,peripherals
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/speed"
    value: "0.59999999999999998"

- name: gnome | peripherals | increase cursor speed (touchpad)
  tags: gnome,mouse,peripherals
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/speed"
    value: "0.59999999999999998"





#####################
# plugins      #
#####################
- name: gnome | peripherals | set manual night-light schedule
  tags: gnome,peripherals,night-light
  become_user: rocket
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic"
    value: "false"

- name: gnome | peripherals | set manual night-light schedule start time
  tags: gnome,peripherals,night-light
  become_user: rocket
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from"
    value: "20.0"

- name: gnome | peripherals | set manual night-light schedule stop time
  tags: gnome,peripherals,night-light
  become_user: rocket
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-to"
    value: "7.0"

- name: gnome | peripherals | enable night-light
  tags: gnome,peripherals,night-light
  become_user: rocket
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"

- name: gnome | peripherals | set power button behavior
  tags: gnome,peripherals,power
  become_user: rocket
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
    value: "'suspend'"

- name: gnome | peripherals | enable automatic suspend while plugged in to ac
  tags: gnome,peripherals,power
  become_user: rocket
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
    value: "'suspend'"

- name: gnome | peripherals | set timeout for automatic suspend while plugged in to ac
  tags: gnome,peripherals,power
  become_user: rocket
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: "2700"

- name: gnome | peripherals | enable automatic suspend while on battery
  tags: gnome,peripherals,power
  become_user: rocket
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type"
    value: "'suspend'"

- name: gnome | peripherals | set timeout for automatic suspend while plugged in to ac
  tags: gnome,peripherals,power
  become_user: rocket
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout"
    value: "1500"


#####################
# Shell             #
#####################

- name: gnome | shell settings | button-layout
  tags: gnome,gnome-shell
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "':minimize,maximize,close'"

# Disable hot corners
- name: gnome | shell settings | enable-hot-corners
  tags: gnome,gnome-shell
  become_user: rocket
  dconf:
    key: "/org/gnome/shell/interface/enable-hot-corners"
    value: "false"

- name: gnome | shell settings | event-sounds (disable)
  tags: gnome,audio,sounds,alerts
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/sound/event-sounds"
    value: "false"

- name: gnome | shell settings | disable hidpi-daemon
  tags: gnome,gnome-shell,hidpi
  become_user: rocket
  dconf:
    key: "/com/system76/hidpi/enable"
    value: "false"
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]

# Disable screen blanking
- name: gnome | shell settings | idle-delay
  tags: gnome,gnome-shell
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/session/idle-delay"
    value: "uint32 0"

# Disable input sounds
- name: gnome | shell settings | input-feedback-sounds (disable input sounds)
  tags: gnome,audio,sounds,alerts
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/sound/input-feedback-sounds"
    value: "false"

# Disable automatic screen lock
- name: gnome | shell settings | lock-enabled
  tags: gnome,gnome-shell
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/screensaver/lock-enabled"
    value: "false"

- name: gnome | shell settings | old-files-age
  tags: gnome,gnome-shell
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/privacy/old-files-age"
    value: "uint32 14"

- name: gnome | shell settings | remove-old-temp-files
  tags: gnome,gnome-shell
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/privacy/remove-old-temp-files"
    value: "true"

- name: gnome | shell settings | remove-old-trash-files
  tags: gnome,gnome-shell
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/privacy/remove-old-trash-files"
    value: "true"

- name: gnome | shell settings | search-providers
  tags: gnome,search
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/search-providers/disabled"
    value: "['org.gnome.Nautilus.desktop', 'org.gnome.Calculator.desktop', 'org.gnome.seahorse.Application.desktop', 'org.gnome.Photos.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Documents.desktop', 'org.gnome.Contacts.desktop', 'org.gnome.Calendar.desktop']"

- name: gnome | shell settings | show-battery-percentage
  tags: gnome,gnome-shell
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

# Disable lock screen notifications
- name: gnome | shell settings | show-in-lock-screen
  tags: gnome,gnome-lockscreen
  become_user: rocket
  dconf:
    key: "/org/gnome/desktop/notifications/show-in-lock-screen"
    value: "false"

- name: gnome | shell settings | tile-by-default
  tags: gnome,gnome-lockscreen
  become_user: rocket
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/tile-by-default"
    value: "true"
  when: ansible_distribution == "Pop!_OS"

- name: gnome | shell settings | workspaces-only-on-primary
  tags: gnome,gnome-shell
  become_user: rocket
  dconf:
    key: "/org/gnome/shell/overrides/workspaces-only-on-primary"
    value: "true"

#- name: gnome | shell settings | set gnome-screenshot default save directory
#  tags: gnome,gnome-shell
#  become_user: rocket
#  dconf:
#    key: "/org/gnome/gnome-screenshot/auto-save-directory"
#    value: "'/home/rocket'"

 #- name: ignore lid close
 #     become: true
 #     lineinfile:
 #       path: /etc/systemd/logind.conf
 #       regexp: '^HandleLidSwitch='
 #       insertafter: '^#HandleLidSwitch='
 #       line: 'HandleLidSwitch=ignore'

- name: automount
  dconf:
    key: "/org/gnome/desktop/media-handling/automount"
    value: "true"

###################
# profile picture #
###################

#- name: verify profile picture
#  stat:
#    path: /var/lib/AccountsService/icons/carl
#  register: profile_picture
#
#- name: download profile picture
#  become: true
#  get_url:
#    url: https://carl.george.computer/me.png
#    dest: /var/lib/AccountsService/icons/carl
#    force: true
#  when: profile_picture.stat.checksum != 'd402e1effc8030039576856525b378743c53664b'
#
#- name: set profile picture
#  become: true
#  lineinfile:
#    path: /var/lib/AccountsService/users/carl
#    regexp: '^Icon='
#    line: 'Icon=/var/lib/AccountsService/icons/carl'


    #################
    # date and time #
    #################

- name: automatic timezone
  dconf:
    key: "/org/gnome/desktop/datetime/automatic-timezone"
    value: "true"

- name: clock show date
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"

- name: clock format
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"